// Automatically generated by astro-icon
// 11ee3a5e2811e1bdd54c8b52556650b62461cba962db90357b9f277ec35f4c8f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "DDNP"
		| "DickensNotes"
		| "DickensNotesBlue"
		| "menu"
		| "search";
}