// Automatically generated by astro-icon
// 805ca883c11de2e635213ecb594c8e227911c02011e82c8bf9d94e4a74526330

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "DDNP"
		| "DickensNotes"
		| "DickensNotesBlue"
		| "DickensNotesSide"
		| "menu";
}