// Automatically generated by astro-icon
// 530f4f47c593758b5f9229e56803274069ad991ddde469e6aabc9ca4d95fae75

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "DDNP"
		| "DickensNotes"
		| "DickensNotesBlue"
		| "menu";
}